# Generated by Django 3.2.4 on 2021-06-26 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0002_auto_20210626_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', editable=False, max_length=255)),
                ('phone', models.CharField(default='', editable=False, max_length=13)),
                ('email', models.CharField(default='', editable=False, max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('complain', models.TextField()),
                ('place', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=20)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
