# Generated by Django 3.2.4 on 2021-06-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0003_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='report',
            name='phone',
            field=models.CharField(max_length=13),
        ),
    ]
