# Generated by Django 3.2.4 on 2021-06-27 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0005_extendeduser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
